
<div class="header">
	<div class="message">
	FREE SHIPPING on orders above $ 100,00
	</div>
	<div class="logo">
		<a href="http://local.magento.com/">
			<img src="<?php echo $this->getSkinUrl('images/HUB.svg'); ?>" border="0">
		</a>
	</div>`
	<div class="navigation">
		<div class="menu">
			<ul>
				<li><a href="http://local.magento.com/">HOME</a></li>
				<li><a href="">MEN</a></li>
				<li><a href="">WOMEN</a></li>
				<li><a href="">VIDEO</a></li>
				<li><a href="">ABOUT US</a></li>
				<li><a href="">STORES</a></li>
				<li><a href=""><img src="<?php echo $this->getSkinUrl('images/Icon - Search.svg'); ?>" border="0" class="search"></a></li>
				<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/Icon - Account.svg'); ?>" border="0" class="acc"></a></li>
				<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/Icon - Euro.svg'); ?>" border="0" class="euro1"></a></li>
				<li><a href="#"><img src="<?php echo $this->getSkinUrl('images/Icon-Shopping Bag.svg'); ?>" border="0" class="bag"></a></li>
				<li><a href="#" class="balance">€ 1599.00</a></li>
			</ul>
		</div>
	</div>
</div>


<!--<img src="<?php echo $this->getSkinUrl('bkg_body.gif'); ?>" border="0">-->